### ISSUE TITLE
Solutions that should not exist?

### ISSUE THREAD

**Issue by Aurele-Barriere** [mpelleau/AbSolute#1]
Hello,
I'm trying this set of constraints : 

init{
  int x = [-20;20];
  int y = [-1;2];
}

constraints{
  x - y > 1;  
  x - y < 0;
}

When solving this (with the command $ ./solver.opt problems/test.txt ),
I get 
solving ends
Unique solution - #created nodes: 2

I don't think it should be possible.
I've looked at the other problems and I think that the syntax is correct.

What I've tried : 
-using real instead of int : same problem
-using different domains : same problem sometimes. But with y in [0;2] for instance the problem disappear (the solver say that there are no solutions).
-using another precision that the default one (with the option -p). Even with precision 0 or precision 120, I still get one solution
-with not strict inequalities (typing >= and <=) : same problem

I've also tried to locate the said solution. The visualization option does not help.
Thus I've tried to add constraints.
If I add the constraint y>1, no solution. So in the solution, y should be <= 1.
But if I add the constraint y<=1, no solutions either.
Is there a way to print the found solutions (other than the visualization option)?

Maybe I just did something wrong in the syntax or maybe I missed something, but I don't know what.

**Comment by mpelleau** [comment]
Hi Aurèle,

Thanks for your message. We notice this issue, the solver have trouble when
dealing with strict inegalities. I'll send you the lines to print the
solutions.

Regards,
Marie

**Comment by mpelleau** [comment]
Hi Aurèle,

We added the option "-trace" or "-t" that prints the solutions:
./solver.opt problems/test.txt -t

However the issue with the strict inequalities is not yet dealt with. We'll get back to you once this issue is fixed.

Sorry for all the troubles you meet, and don't worry you did nothing wrong :)

Best,
Marie

**Comment by mpelleau** [comment]
Hi Aurèle,

We changed the filter for the strict inequalities. Normally the problem is dealt with, but only with the default box abstract domain.

Let us know if this issue is closed :)

Best,
Marie

**Comment by Aurele-Barriere** [comment]
Thanks for the replies ! The trace option is really useful.

However, I still have a similar problem.

With the constraints 

init{
  int x = [-20000;20000];
  int y = [-1;2];
}

constraints{
  x - y >= 1;  
  x - y <= 0;
}

I get a solution : abs = x%:[1.;1.] y%:[1.;1.]

With strict inequalities, or if I change the domain of y to [0;2], the problem disappears.

But somehow the solver thinks that 1 - 1 >= 1.

Have a good day,
Aurèle

**Comment by ghilesZ** [comment]
Hi Aurele,

The thing users have to know about absolute is that it returns a list of
abstract elements (boxes, octagons ...) that MAY satisfy the set of
constraints (because of the framework we use handles : approximation,
over-approximations in our case).
Absolute checks if an element satisfies the set of constraint, the answer
being either YES or MAYBE.
I've just pushed on github small changes on the printer:
It prints either:
- sure:x=[0;1]
Or
- unsure:x=[0;1]

for each solution found.

Best regards,
Ghiles.



2016-06-01 9:21 GMT+02:00 Aurèle <notifications@github.com>:

**Comment by Aurele-Barriere** [comment]
Hi, thank you. I assumed (badly) that the printed solutions were only the sure ones.
The printer makes it very clear now.

Thanks for your help,
Aurèle
